name: Release Add-On Pipeline

on:
  workflow_dispatch:
  # push:
  #   branches: [ "master" ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os-type }}

    strategy:
      matrix:
        os-type: [ windows-2019, macos-12 ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Checkout the submodule
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Run build script
        run: |
          python Tools/buildAddOn.py --configFile config.json --release --package

      - name: Set release tag
        id: setTag
        run: |
          if [[ $(git tag | grep '^v') ]]
          then
            newTag=$(git tag | grep '^v'| tail -1 | awk -F'.' '/^v/{split($1,a,"v"); print "v" a[2]+1 ".0"}')
          else
            newTag=v1.0
          fi
          echo "newTag=$newTag" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.setTag.outputs.newTag }}
          files: "${{ github.workspace }}/Build/Package/*.zip"
            
            
      
